kaggle:
  datasets:
    - id: 'olistbr/marketing-funnel-olist'
    - id: 'olistbr/brazilian-ecommerce'
  bucket_name: 'kaggle_landing_zone'
  folder: 'bronze'
  compacted_folder: 'compacted'
  unzipped_folder: 'unzipped'
